// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OffenderWatch.TestManagement.Server.Data;

#nullable disable

namespace OffenderWatch.TestManagement.Server.Migrations
{
    [DbContext(typeof(TestManagementDbContext))]
    partial class TestManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.Environment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.EvidenceArtifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScenarioResultId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioResultId");

                    b.ToTable("EvidenceArtifacts");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.ScenarioResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("TestRunId", "TestCaseId")
                        .IsUnique();

                    b.ToTable("ScenarioResults");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BugId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequirementId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Suite")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.TestDataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CleanedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanupStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScenarioResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioResultId");

                    b.HasIndex("EntityType", "ExternalId");

                    b.HasIndex("TestRunId", "CleanupStatus");

                    b.ToTable("TestDataRecords");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.TestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrlSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EnvironmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.EvidenceArtifact", b =>
                {
                    b.HasOne("OffenderWatch.TestManagement.Server.Models.ScenarioResult", "ScenarioResult")
                        .WithMany("EvidenceArtifacts")
                        .HasForeignKey("ScenarioResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScenarioResult");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.ScenarioResult", b =>
                {
                    b.HasOne("OffenderWatch.TestManagement.Server.Models.TestCase", "TestCase")
                        .WithMany("ScenarioResults")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OffenderWatch.TestManagement.Server.Models.TestRun", "TestRun")
                        .WithMany("ScenarioResults")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TestCase");

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.TestDataRecord", b =>
                {
                    b.HasOne("OffenderWatch.TestManagement.Server.Models.ScenarioResult", "ScenarioResult")
                        .WithMany("TestDataRecords")
                        .HasForeignKey("ScenarioResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OffenderWatch.TestManagement.Server.Models.TestRun", "TestRun")
                        .WithMany("TestDataRecords")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScenarioResult");

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.TestRun", b =>
                {
                    b.HasOne("OffenderWatch.TestManagement.Server.Models.Environment", "Environment")
                        .WithMany("TestRuns")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.Environment", b =>
                {
                    b.Navigation("TestRuns");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.ScenarioResult", b =>
                {
                    b.Navigation("EvidenceArtifacts");

                    b.Navigation("TestDataRecords");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.TestCase", b =>
                {
                    b.Navigation("ScenarioResults");
                });

            modelBuilder.Entity("OffenderWatch.TestManagement.Server.Models.TestRun", b =>
                {
                    b.Navigation("ScenarioResults");

                    b.Navigation("TestDataRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
